// @flow
export const CREATE_REPORT = "CREATE_REPORT";
export const DELETE_REPORT_FAIL = "DELETE_REPORT_FAIL";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const RESET = "RESET";
export const SELECT_REPORT = "SELECT_REPORT";
export const UPDATE_REPORT = "UPDATE_REPORT";
export const SAVE_REPORT_FAIL = "SAVE_REPORT_FAIL";
export const SAVE_REPORT_SUCCESS = "SAVE_REPORT_SUCCESS";
export const FETCH_REPORTS_FAIL = "FETCH_REPORTS_FAIL";
export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const INITIALIZE_FAIL = "INITIALIZE_FAIL";
export const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";